# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - "berrycloud/reviewers"
    groups:
      spring-boot-dependencies:
        patterns:
          - "org.springframework.boot:*"
          - "org.springframework.integration:*"
      squareup-dependencies:
        patterns:
          - "com.squareup.*:*"
      jsonwebtoken-dependencies:
        patterns:
          - "io.jsonwebtoken:*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      auto-merge-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "actions/checkout"
          - "actions/create-github-app-token"
          - "actions/setup-java"
          - "actions/stale"
          - "advanced-security/maven-dependency-submission-action"
          - "dependabot/fetch-metadata"
          - "github/codeql-action"
